### ISSUE TITLE
Replace chrono with time 0.3 for cargo audit reports

### ISSUE THREAD

**Issue by sunng87** [influxdb-rs/influxdb-rust#108]
The current release chrono depends on time 0.1.x, which has [an issue](https://github.com/chronotope/chrono/issues/499) reported by `cargo audit`. Also chrono doesn't seem to be well maintained. Its latest version was released 16 months ago. `time` 0.3.x provides similar functionalities to `chrono` and could be a good replacement for it.

**Comment by msrd0** [comment]
Oops, chrono should not depend on time 0.1. I hate that that's enabled by default.
