### ISSUE TITLE
Clearly state in README that only 1.x is working

### ISSUE THREAD

**Issue by Mazwak** [influxdb-rs/influxdb-rust#111]
I tried to use the library and couldn’t see how to connect to v2.

I then realized it was only for v1.x, which was confirmed by the issue.

You should put a big notice at the beginning that it is only for v1.

**Comment by Empty2k12** [comment]
This project has been built before 2.0 was even released. Feel free to open a PR to clarify.

**Comment by msrd0** [comment]
Since #118 you can also connect to influxdb 2.0
